### PR TITLE
Password Entry Modified

### PR DESCRIPTION
**Pull request by laveesingh**
I saw your code. It was wonderful. I tried it but when I entered the password, it was not hidden and I thought it is not a good feature. So I tried to modify this feature. I used getpass() function from getpass module to get user-password instead of raw_input(). Take a test of the modification and please merge it if you think it's good change.

### CODE REVIEW

**Comment by dhruvagarwal** [comment]
Thanks for using this script @laveesingh and contributing to it :+1:

**Comment by laveesingh** [comment]
The pleasure is all mine. Well, I'm a, kind of, newbie, and I always seek
guidance I want to work on something like building chrome-extension or
creating command-line software for linux. But I don't have any guidance or
any support. Could you give me some idea, just some basic, where I should
seek help, and what I need to learn for it? Thanks in advance! 👍👍👍

**Comment by dhruvagarwal** [comment]
@laveesingh That's great that you have these interests. There is no direct place you can find but there's a hyper community of devs online, where you can seek help directly by mailing or any other form of contact. You can discuss with devs or post it on stackoverflow or quora and its very likely that you'll get some solution or help.

BTW you can shoot me a mail if you want to discuss anything , i share common interests :)

**Comment by laveesingh** [comment]
Thanks, Well, I've great interest in google-app-engine, can you tell me
what do I need to learn and in what order, or can you give me some link or
resource of this kind of thing! This would be of great help. Thanks again!

**Pull request merged**
